#!/bin/bash

#Funcion del menu, me muestra el menu por pantalla.
menu (){
	clear
	echo "1.-Comprimir"
	echo "2.-Descomprimir"
	echo "0.-Exit"
	read opcion
	#return $operacion guarda el numero que as seleccionado en $?
}

#Funcion que comprime
comprimir (){
	echo "Introduce directorio a comprimir situado en el escritorio"
read archivo

if [ -d $archivo ]
	then
cd ~/Escritorio
	tar cvf ~/Escritorio/$archivo.tgz $archivo

else
echo ""
echo "" 
echo "$archivo no es un directorio y no se puede comprimir"
fi
}

#Funcion que descomprime
descomprimir (){ 
        echo "Introduce directorio para descomprimir situado en el escritorio"
	read archivo
if [ -d $archivo ]
cd ~/Escritorio
then 	
	 tar -xvf $archivo 
else 
echo ""
echo ""
echo "$archivo no es un directorio y no se puede descomprimir"
fi
}


#Funcion hace que al elegir una opcion se ejecute las funciones arriba hechas
opciones (){
case $opcion in
	1)comprimir;;
	2)descomprimir;;
	0)exit 0;;
esac
}


while true
do
#Llama a la funcion menu y me muestra el menu
 menu
if [ $opcion -le 2 ] && [ $opcion -ge 0 ] 
then
#Llamo a la funcion opciones.
opciones
#Muestro el resultado por pantalla.
else  echo "OPCION NO DISPOBIBLE"
fi
read -p "Pulse cualquier tecla para continuar"

done
